# Generated by Django 2.2.10 on 2020-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsafety_1',
            name='s1_e4_res',
            field=models.FloatField(),
        ),
    ]
