# Generated by Django 2.2.6 on 2019-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aed_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cant_test',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecg_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowmeter_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infusion_pump_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_spo2_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monometer_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
