# Generated by Django 2.2.6 on 2019-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecg_1',
            old_name='s1_e1_Ramp',
            new_name='s1_e1_ramp',
        ),
        migrations.RenameField(
            model_name='ecg_1',
            old_name='s1_e2_Ramp',
            new_name='s1_e2_ramp',
        ),
        migrations.RenameField(
            model_name='ecg_1',
            old_name='s1_e3_Ramp',
            new_name='s1_e3_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s6_e1_Ramp',
            new_name='s6_e1_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s6_e2_Ramp',
            new_name='s6_e2_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s6_e3_Ramp',
            new_name='s6_e3_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s7_e1_Ramp',
            new_name='s7_e1_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s7_e2_Ramp',
            new_name='s7_e2_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s7_e3_Ramp',
            new_name='s7_e3_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s7_e4_Ramp',
            new_name='s7_e4_ramp',
        ),
        migrations.RenameField(
            model_name='monitor_ecg_1',
            old_name='s7_e5_Ramp',
            new_name='s7_e5_ramp',
        ),
        migrations.RenameField(
            model_name='ventilator_1',
            old_name='s12_e1',
            new_name='s12_e1_o2',
        ),
        migrations.RenameField(
            model_name='ventilator_1',
            old_name='s12_e2',
            new_name='s12_e1_o2n2o',
        ),
        migrations.RenameField(
            model_name='ventilator_1',
            old_name='s1_e1_res',
            new_name='s1_res',
        ),
        migrations.RemoveField(
            model_name='spo2_1',
            name='s6_e1_pe',
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e1_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e1_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e2_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e2_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e3_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e3_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e4_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e4_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e5_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e5_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e6_aclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e6_dclc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s5_e1_bflc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s5_e1_cflc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s7_e1_si1',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s7_e1_si2',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s7_e1_si3',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s7_e1_si4',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='se_e1_comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='se_e1_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='se_e2_comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='se_e2_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monometer_1',
            name='s2_e1_np',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monometer_1',
            name='s2_e2_np',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monometer_1',
            name='s2_e3_np',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monometer_1',
            name='s2_e4_np',
            field=models.IntegerField(),
        ),
    ]
