# Generated by Django 2.2.6 on 2019-12-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecg_1',
            name='s14_e1_pe',
        ),
    ]
