# Generated by Django 2.2.6 on 2019-11-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e10_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e11_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e12_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e13_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e14_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e15_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e16_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e17_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e18_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e19_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e1_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e20_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e21_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e22_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e23_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e2_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e3_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e4_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e5_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e6_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e7_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e8_status',
        ),
        migrations.RemoveField(
            model_name='syringe_pump_1',
            name='s0_e9_status',
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e10comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e11comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e12_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e12comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e13_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e13comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e14_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e14comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e15_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e15comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e16_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e16comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e17_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e17comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e18_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e18comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e19_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e19comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e20_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e20comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e21_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e21comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e22_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e22comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e23_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e23comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e2comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e3comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e4comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e5comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e6comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e7comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e8comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s0_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s0e9comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s1e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s1_e2_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s1e2comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s2_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s2e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s2_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s2e2comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s2_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s2e3comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s2_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s2e4comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s2_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s2e5comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s3e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s3_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s3e2comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s3_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s3e3comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s3_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s3e4comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s3_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s3e5comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e2comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e3comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e4comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e5_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e5comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s4_e6_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s4e6comment', to='acc.quantitive_comment_syringe_pump'),
        ),
        migrations.AlterField(
            model_name='syringe_pump_1',
            name='s5_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spmp1s5e1comment', to='acc.quantitive_comment_syringe_pump'),
        ),
    ]
