# Generated by Django 2.2.6 on 2019-12-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defibrilator_1',
            name='s7d_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7de1comment', to='acc.comment'),
        ),
        migrations.AddField(
            model_name='defibrilator_1',
            name='s7d_e1_ec',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defibrilator_1',
            name='s7d_e1_en',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defibrilator_1',
            name='s7d_e1_es',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
