# Generated by Django 2.2.6 on 2019-11-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aed_1',
            options={'verbose_name_plural': 'AED'},
        ),
        migrations.AlterModelOptions(
            name='anesthesia_machine_1',
            options={'verbose_name_plural': 'Anesthesia Machine'},
        ),
        migrations.AlterModelOptions(
            name='cant_test',
            options={'verbose_name_plural': '1_Can,t Test'},
        ),
        migrations.AlterModelOptions(
            name='defibrilator_1',
            options={'verbose_name_plural': 'Defibrilator'},
        ),
        migrations.AlterModelOptions(
            name='ecg_1',
            options={'verbose_name_plural': 'ElectroCardioGraph'},
        ),
        migrations.AlterModelOptions(
            name='electrocauter_1',
            options={'verbose_name_plural': 'ElectroCauter'},
        ),
        migrations.AlterModelOptions(
            name='flowmeter_1',
            options={'verbose_name_plural': 'Flow Meter'},
        ),
        migrations.AlterModelOptions(
            name='infusion_pump_1',
            options={'verbose_name_plural': 'Infusion Pump'},
        ),
        migrations.AlterModelOptions(
            name='monitor_ecg_1',
            options={'verbose_name_plural': 'Monitor ECG'},
        ),
        migrations.AlterModelOptions(
            name='monitor_nibp_1',
            options={'verbose_name_plural': 'Monitor NIBP'},
        ),
        migrations.AlterModelOptions(
            name='monitor_safety_1',
            options={'verbose_name_plural': 'Monitor Safety'},
        ),
        migrations.AlterModelOptions(
            name='monitor_spo2_1',
            options={'verbose_name_plural': 'Monitor SPO2'},
        ),
        migrations.AlterModelOptions(
            name='monometer_1',
            options={'verbose_name_plural': 'ManoMeter'},
        ),
        migrations.AlterModelOptions(
            name='spo2_1',
            options={'verbose_name_plural': 'PulseOxyMeter'},
        ),
        migrations.AlterModelOptions(
            name='suction_1',
            options={'verbose_name_plural': 'Suction'},
        ),
        migrations.AlterModelOptions(
            name='syringe_pump_1',
            options={'verbose_name_plural': 'Syringe Pump'},
        ),
        migrations.AlterModelOptions(
            name='ventilator_1',
            options={'verbose_name_plural': 'Ventilator'},
        ),
    ]
