# Generated by Django 2.2.6 on 2019-10-29 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc', '0005_comment_cant_test'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cant_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.All_Device')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr', to='acc.record')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.Request')),
                ('totalcomment', models.ManyToManyField(related_name='cttotalcomment', to='acc.comment_cant_test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
