# Generated by Django 2.2.6 on 2019-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_ad_test_type0'),
        ('form', '0002_cant_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cant_test',
            name='tt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acc.ad_test_type0'),
            preserve_default=False,
        ),
    ]
