# Generated by Django 2.2.6 on 2019-11-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191110_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7d_e1_comment',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7d_e1_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7d_e1_en',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7d_e1_es',
        ),
    ]
