# Generated by Django 2.2.10 on 2020-04-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200310_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiamachine_1',
            name='s13_e3_o2p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesiamachine_1',
            name='s13_e3_ro2c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesiamachine_1',
            name='s13_e3_ro2d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4c_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4c_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4c_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4d_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4d_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4d_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4e_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4e_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4e_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4f_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4f_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4f_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4g_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4g_e1_p2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4g_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4g_e2_p2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4m_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4m_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4n_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrocauter_1',
            name='s4n_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infusionpump_1',
            name='s6_e1_mf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infusionpump_1',
            name='s6_e2_mf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infusionpump_1',
            name='s7_e1_mmf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infusionpump_1',
            name='s7_e2_mmf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e10_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e10_spo2',
            field=models.IntegerField(default=98),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e11_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e11_spo2',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e1_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e1_spo2',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e2_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e2_spo2',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e3_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e3_spo2',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e4_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e4_spo2',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e5_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e5_spo2',
            field=models.IntegerField(default=88),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e6_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e6_spo2',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e7_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e7_spo2',
            field=models.IntegerField(default=92),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e8_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e8_spo2',
            field=models.IntegerField(default=94),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e9_pr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s2_e9_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e1_accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s3e1accessory', to='acc.Accessory'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s3e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e1_pr',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e1_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e2_pr',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e2_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e3_pr',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e3_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e4_pr',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e4_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e5_pr',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s3_e5_spo2',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e2comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e3comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e4comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s6_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s6e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s7e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s7e2comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='syringepump_1',
            name='s6_e1_mf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='syringepump_1',
            name='s6_e2_mf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='syringepump_1',
            name='s7_e1_mmf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='syringepump_1',
            name='s7_e2_mmf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_1e1',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_1e2',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_1e3',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_e1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_e3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_e4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_e6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s16_e7',
            field=models.FloatField(default=-1),
        ),
    ]
