# Generated by Django 2.2.6 on 2019-10-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191003_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_spo2_1',
            name='s1_e1_status',
        ),
        migrations.RemoveField(
            model_name='monitor_spo2_1',
            name='s1_e2_status',
        ),
        migrations.AlterField(
            model_name='monitor_spo2_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ms1s1e1comment', to='acc.quantitive_comment_monitor_spo2'),
        ),
        migrations.AlterField(
            model_name='monitor_spo2_1',
            name='s1_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ms11s1e2comment', to='acc.quantitive_comment_monitor_spo2'),
        ),
        migrations.AlterField(
            model_name='monitor_spo2_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ms1s4e1comment', to='acc.quantitive_comment_monitor_spo2'),
        ),
    ]
