# Generated by Django 2.2.10 on 2020-03-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200302_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7d_e1_ec',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s13_e1_va',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s13_e1_watt',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s1_e1_damp',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s1_e2_damp',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s1_e3_damp',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e1_1',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e1_m',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e1_s',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e2_1',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e2_m',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e2_s',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e3_1',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e3_m',
        ),
        migrations.RemoveField(
            model_name='electrocauter_1',
            name='s3c_e3_s',
        ),
        migrations.RemoveField(
            model_name='spo2_1',
            name='s5_e1_va',
        ),
        migrations.RemoveField(
            model_name='spo2_1',
            name='s5_e1_watt',
        ),
        migrations.RemoveField(
            model_name='ventilator_1',
            name='s6_e1_ffr',
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='test_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='aed1tt', to='acc.AdTestType'),
        ),
        migrations.AlterField(
            model_name='anesthesiamachine_1',
            name='s17_e3',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='anesthesiamachine_1',
            name='s17_e4',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e1_hr',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e2_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e3_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e4_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e7_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e8_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s3_e9_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s8_e1_bdisp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s8_e1_slope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e10_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e1_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e2_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e3_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e4_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e5_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e6_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e7_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e8_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s1_e9_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e1_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e2_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e3_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e4_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e5_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e6_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e7_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suction_1',
            name='s2_e8_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s14_e1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s14_e2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ventilator_1',
            name='s14_e3',
            field=models.FloatField(),
        ),
    ]
