# Generated by Django 2.2.10 on 2020-04-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200410_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7a_e1_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7a_e2_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7a_e3_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7c_e1_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7c_e2_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s7c_e3_ec',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s8_e1_ec',
        ),
    ]
