# Generated by Django 2.2.6 on 2019-10-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20191003_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_spo2_1',
            name='s4_e1_status',
        ),
    ]
