# Generated by Django 2.2.6 on 2019-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_cant_test_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cant_test',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
