# Generated by Django 2.2.6 on 2019-10-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_monitor_spo2_1_s4_e1_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defibrilator_1',
            old_name='s12_e1_dc',
            new_name='s12_e1_cc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e22_lc',
            new_name='s5_e10_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e23_lc',
            new_name='s5_e11_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e24_lc',
            new_name='s5_e12_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e25_lc',
            new_name='s5_e13_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e26_lc',
            new_name='s5_e14_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e27_lc',
            new_name='s5_e15_lc',
        ),
        migrations.RenameField(
            model_name='monitor_safety_1',
            old_name='s4_e28_lc',
            new_name='s5_e1_lc',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e10_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e11_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e12_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e13_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e14_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e15_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e16_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e17_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e18_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e19_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e1_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e20_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e21_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e22_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e23_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e24_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e25_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e26_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e27_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e28_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e29_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e2_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e30_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e31_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e3_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e4_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e5_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e6_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e7_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e8_status',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s0_e9_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e10_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e11_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e12_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e13_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e14_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e15_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e16_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e17_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e18_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e19_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e1_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e20_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e21_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e22_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e2_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e3_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e4_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e5_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e6_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e7_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e8_status',
        ),
        migrations.RemoveField(
            model_name='defibrilator_1',
            name='s0_e9_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s11_e1_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s11_e2_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s11_e3_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s11_e4_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s11_e5_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s12_e1_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s12_e2_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s12_e3_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s12_e4_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e1_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e2_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e3_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e4_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e5_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e6_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e7_status',
        ),
        migrations.RemoveField(
            model_name='ecg_1',
            name='s7_e8_status',
        ),
        migrations.RemoveField(
            model_name='monitor_ecg_1',
            name='s5_e1_status',
        ),
        migrations.RemoveField(
            model_name='monitor_ecg_1',
            name='s9_e1_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s1_e1_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s1_e2_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s1_e3_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s1_e4_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s2_e1_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s2_e2_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e1_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e2_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e3_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e4_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e5_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s3_e6_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e10_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e11_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e12_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e13_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e14_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e15_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e16_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e17_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e18_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e19_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e1_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e20_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e21_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e22_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e23_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e24_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e25_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e26_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e27_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e28_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e2_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e3_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e4_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e5_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e6_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e7_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e8_comment',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s4_e9_comment',
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e2_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e3_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e4_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e5_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e6_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e7_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e8_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='s5_e9_lc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e10comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e11comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e12_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e12comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e13_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e13comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e2comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e3comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e4comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e5comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e6comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e7comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e8comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s0_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s0e9comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s11_e2_t',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s11_e3_t',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s12_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s12e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s1e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e2comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e3comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e4comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e5comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e6comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s2_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s2e7comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e2comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e3comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e4comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e5comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e6comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s3_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s3e7comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e10comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e2comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e3comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e4comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e5comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e6comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e7comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e8comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s4_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s4e9comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e10comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e2comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e3comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e4comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e5comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e6comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e7comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e8comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s5_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s5e9comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s6_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aed1s6e1comment', to='acc.quantitive_comment_aed'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e10comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e11comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e12_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e12comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e13_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e13comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e14_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e14comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e15_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e15comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e16_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e16comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e17_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e17comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e18_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e18comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e19_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e19comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e20_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e20comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e21_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e21comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e22_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e22comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e23_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e23comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e24_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e24comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e25_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e25comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e26_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e26comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e27_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e27comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e28_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e28comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e29_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e29comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e30_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e30comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e31_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e31comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e3comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e4comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e5comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e6comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e7comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e8comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s0_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s0e9comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s1e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s1_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s1e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s2_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s2e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s2_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s2e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s2_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s2e3comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s2_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s2e4comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s2_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s2e5comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s3e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s3_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s3e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s3_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s3e3comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s3_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s3e4comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s3_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s3e5comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e3comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e4comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e5_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e5comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s4_e6_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s4e6comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='anesthesia_machine_1',
            name='s5_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='am1s5e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e10comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e11comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e12_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e12comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e13_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e13comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e14_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e14comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e15_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e15comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e16_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e16comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e17_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e17comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e18_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e18comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e19_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e19comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e20_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e20comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e21_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e21comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e22_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e22comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e8comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s0_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s0e9comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e10comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e8comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s10_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s10e9comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s11_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s11e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s12_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s12e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s12_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s12e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s12_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s12e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s1e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s2_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s2e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s3_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s3e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e10comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e8comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s4e9comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e10comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e4comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e5comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e6comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e7comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e8comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s5e9comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s6_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s6e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7a_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ae1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7a_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ae2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7a_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ae3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7b_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7be1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7b_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7be2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7b_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7be3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7c_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ce1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7c_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ce2comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7c_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7ce3comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s7d_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s7de1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s8_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s8e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s9_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='df1s9e1comment', to='acc.quantitive_comment_defibrilator'),
        ),
        migrations.AlterField(
            model_name='ecg_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='e1s1e1comment', to='acc.quantitive_comment_ecg'),
        ),
        migrations.AlterField(
            model_name='ecg_1',
            name='s1_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='e1s1e2comment', to='acc.quantitive_comment_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e4comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e5comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e6comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e7comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s1_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s1e8comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e10comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e4comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e5comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e6comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e7comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e8comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s2_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s2e9comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e10comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e11comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e12_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e12comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e4comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e5comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e6comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e7comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e8comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s3_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s3e9comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s4e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s5_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s5e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s5_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s5e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s5_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s5e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s5_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s5e4comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s6e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e1_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s6e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e2_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s6e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s6_e3_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s7e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e1_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s7e2comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e2_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s7e3comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e3_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s7e4comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e4_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s7e5comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s7_e5_ramp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s8_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s8e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_ecg_1',
            name='s9_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='me1s9e1comment', to='acc.quantitive_comment_monitor_ecg'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e10comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e11_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e11comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e12_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e12comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e13_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e13comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e14_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e14comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e15_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e15comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e16_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e16comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e17_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e17comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e18_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e18comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e19_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e19comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e1comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e20_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e20comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e21_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e21comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e22_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e22comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e2comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e3comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e4comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e5comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e6comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e7comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e8comment', to='acc.quantitive_comment_monitor_safety'),
        ),
        migrations.AlterField(
            model_name='monitor_safety_1',
            name='s0_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1s0e9comment', to='acc.quantitive_comment_monitor_safety'),
        ),
    ]
