# Generated by Django 2.2.10 on 2020-04-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200410_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anesthesiamachine_1',
            name='s13_e3_o2p',
        ),
        migrations.RemoveField(
            model_name='anesthesiamachine_1',
            name='s13_e3_ro2c',
        ),
        migrations.RemoveField(
            model_name='anesthesiamachine_1',
            name='s13_e3_ro2d',
        ),
        migrations.RemoveField(
            model_name='anesthesiamachine_1',
            name='s14_e1',
        ),
        migrations.RemoveField(
            model_name='anesthesiamachine_1',
            name='s14_e2',
        ),
    ]
