# Generated by Django 2.2.5 on 2019-10-07 19:25

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20191003_1907'),
        ('form', '0005_auto_20191007_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e10_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e11_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e12_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e13_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e14_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e15_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e16_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e17_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e18_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e19_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e1_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e20_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e21_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e22_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e2_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e3_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e4_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e5_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e6_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e7_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e8_status',
        ),
        migrations.RemoveField(
            model_name='monitor_safety_1',
            name='s0_e9_status',
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='cal_dev3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='msa1caldev3', to='acc.Cal_device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='cal_dev_3_cd',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor_safety_1',
            name='cal_dev_3_xd',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
