# Generated by Django 2.2.5 on 2019-10-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20191007_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e10_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e11_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e12_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e13_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e1_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e2_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e3_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e4_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e5_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e6_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e7_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e8_status',
        ),
        migrations.RemoveField(
            model_name='aed_1',
            name='s0_e9_status',
        ),
        migrations.AlterField(
            model_name='aed_1',
            name='s1_e1_res',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e1_simp',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e2_simp',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e3_simp',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e4_simp',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e5_simp',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e6_simp',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e7_simp',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='monitor_nibp_1',
            name='s1_e8_simp',
            field=models.IntegerField(default=200),
        ),
    ]
