# Generated by Django 2.2.5 on 2019-10-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20191003_1907'),
        ('form', '0007_auto_20191008_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s13_e1_ro2n20f',
        ),
        migrations.RemoveField(
            model_name='anesthesia_machine_1',
            name='s13_e2_ro2n20f',
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s13_e1_ro2n2of',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s13_e2_ro2n2of',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s13_me',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e10_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e10comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e1comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e2_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e2comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e3_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e3comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e4_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e4comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e5_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e5comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e6_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e6comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e7_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e7comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e8_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e8comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
        migrations.AddField(
            model_name='anesthesia_machine_1',
            name='s18_e9_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='am1s18e9comment', to='acc.quantitive_comment_anesthesia_machine'),
        ),
    ]
