# Generated by Django 2.2.6 on 2019-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'سابقه گزارشات'},
        ),
        migrations.AlterField(
            model_name='report',
            name='totalcomment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
