# Generated by Django 2.2.6 on 2019-12-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='el', to='acc.licence')),
            ],
        ),
    ]
