# Generated by Django 2.2.6 on 2019-11-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rl', to='acc.licence'),
        ),
        migrations.AlterField(
            model_name='report',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr', to='acc.record'),
        ),
        migrations.DeleteModel(
            name='licence',
        ),
        migrations.DeleteModel(
            name='record',
        ),
    ]
