# Generated by Django 2.2.6 on 2019-12-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('report', '0002_encode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encode',
            name='licence',
        ),
        migrations.AddField(
            model_name='encode',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='el', to='acc.Hospital'),
            preserve_default=False,
        ),
    ]
