# Generated by Django 2.2.10 on 2020-03-10 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.Company', verbose_name='شرکت سازنده'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام لوازم جانبی'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.DeviceType', verbose_name='نوع لوازم جانبی'),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Hospital', verbose_name='نام بیمارستان'),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Device', verbose_name='نام مدل دستگاه'),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='property_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره اموال دستگاه'),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Section', verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='serial_number',
            field=models.TextField(blank=True, null=True, verbose_name='شماره سریال دستگاه'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='calibration_Expire_date',
            field=models.DateField(verbose_name='تاریخ اتمام کالیبراسیون'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='calibration_date',
            field=models.DateField(verbose_name='تاریخ شروع کالیبراسیون'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Company', verbose_name='شرکت سازنده'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='name',
            field=models.TextField(verbose_name='نام دستگاه کالیبره'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='serial',
            field=models.CharField(max_length=30, verbose_name='سریال دستگاه کالیبره'),
        ),
        migrations.AlterField(
            model_name='caldevice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.DeviceType', verbose_name='نوع دستگاه'),
        ),
        migrations.AlterField(
            model_name='city',
            name='eng_name',
            field=models.TextField(verbose_name='نام انگلیسی شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.State', verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=50, verbose_name='شرح توضیح'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='company',
            name='en_name',
            field=models.TextField(verbose_name='نام انگلیسی شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='device',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Company', verbose_name='شرکت سازنده'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(verbose_name='اسم مدل دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.DeviceType', verbose_name='نوع دستگاه'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.TextField(verbose_name='نوع دستگاه'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(verbose_name='آدرس بیمارستان'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.City', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.TextField(verbose_name='نام بیمارستان'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربری بیمارستان'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='number',
            field=models.IntegerField(verbose_name='شماره گواهی'),
        ),
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره رکورد'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ میلادی دستگاه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Hospital', verbose_name='نام بیمارستان'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.IntegerField(verbose_name='شماره درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acc.AdReqStatus', verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='section',
            name='eng_name',
            field=models.TextField(verbose_name='نام انگلیسی بخش'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Country', verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='state',
            name='eng_name',
            field=models.TextField(verbose_name='نام انگلیسی استان'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.TextField(verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatar/', verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/', verbose_name='تصویر امضا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر'),
        ),
    ]
