# Generated by Django 2.2.8 on 2020-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='eng_name',
            field=models.TextField(default='N.A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='eng_name',
            field=models.TextField(default='N.A'),
            preserve_default=False,
        ),
    ]
