# Generated by Django 2.2.6 on 2019-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_test_type2',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
