# Generated by Django 2.2.6 on 2019-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_device',
            name='property_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_device',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
