# Generated by Django 2.2.6 on 2019-11-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'لوازم جانبی'},
        ),
        migrations.AlterModelOptions(
            name='ad_acc_status',
            options={'verbose_name_plural': 'سلسله مراتب حسابها'},
        ),
        migrations.AlterModelOptions(
            name='ad_az_status',
            options={'verbose_name_plural': 'وضعیت های آزمایش'},
        ),
        migrations.AlterModelOptions(
            name='ad_excel_arg',
            options={'verbose_name_plural': 'آرگومان اکسل'},
        ),
        migrations.AlterModelOptions(
            name='ad_req_status',
            options={'verbose_name_plural': 'وضعیت های درخواست'},
        ),
        migrations.AlterModelOptions(
            name='ad_test_type',
            options={'verbose_name_plural': 'کلاس تست'},
        ),
        migrations.AlterModelOptions(
            name='ad_test_type0',
            options={'verbose_name_plural': 'نوع آزمایش'},
        ),
        migrations.AlterModelOptions(
            name='ad_test_type2',
            options={'verbose_name_plural': 'کلاس تست 2'},
        ),
        migrations.AlterModelOptions(
            name='all_device',
            options={'verbose_name_plural': 'دستگاه های ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='auserprofile',
            options={'verbose_name_plural': 'مشخصات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='cal_device',
            options={'verbose_name_plural': 'دستگاه های کنترل کیفی'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'توضیحات'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'شرکت های سازنده'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'کشور ها'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'لیست دستگاه'},
        ),
        migrations.AlterModelOptions(
            name='device_type',
            options={'verbose_name_plural': 'نوع دستگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'بیمارستان ها'},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'verbose_name_plural': 'شماره گواهی'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name_plural': 'پارامتر ها'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': 'شماره رکورد'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'لیست درخواست ها'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'بخش های بیمارستان'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'استان ها'},
        ),
    ]
