# Generated by Django 2.2.6 on 2019-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_acc_status',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ad_az_status',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ad_req_status',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
