# Generated by Django 2.2.6 on 2020-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20200119_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auserprofile',
            name='avatar',
            field=models.ImageField(default='avatar/male-profile-avatar-with-brown-hair-vector-12055105.jpg', upload_to='avatar/'),
        ),
    ]
