# Generated by Django 2.2.6 on 2019-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20191025_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_test_type',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
