# Generated by Django 2.2.6 on 2019-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20191025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auserprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='auserprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
