# Generated by Django 2.2.6 on 2019-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20191025_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_cant_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
