# Generated by Django 2.2.6 on 2019-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_comment_cant_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_test_type0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
